spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
